SELECT
	SUM(下发名单量) 下发总量, SUM(成功数) 成功总数, round(SUM(成功数)/SUM(下发名单量),4) 平均转化率,
	round(SUM(邮件1转化率)/COUNT(*),4) 邮件1平均转化率,
	round(SUM(邮件2转化率)/COUNT(*),4) 邮件2平均转化率,
	round(SUM(邮件3转化率)/COUNT(*),4) 邮件3平均转化率,
	round(SUM(邮件4转化率)/COUNT(*),4) 邮件4平均转化率,
	round(SUM(邮件5转化率)/COUNT(*),4) 邮件5平均转化率,
	round(SUM(邮件6转化率)/COUNT(*),4) 邮件6平均转化率,
	round(SUM(邮件7转化率)/COUNT(*),4) 邮件7平均转化率,
	round(SUM(邮件8转化率)/COUNT(*),4) 邮件8平均转化率,
	round(SUM(邮件9转化率)/COUNT(*),4) 邮件9平均转化率,
	round(SUM(邮件10转化率)/COUNT(*),4) 邮件10平均转化率,
	round(SUM(邮件20转化率)/COUNT(*),4) 邮件20平均转化率
FROM 
(
SELECT t.姓名, NVL(f."下发名单量", 0) 下发名单量,NVL( s."成功数", 0) 成功数, round(NVL( s."成功数", 0)/下发名单量,4)*100 转化率,
 
(CASE NVl(s."成功数",0) WHEN 0 THEN 0 ELSE round(NVl(t1."邮件1",0)/s."成功数",4)*100 END) 邮件1转化率,
(CASE NVl(s."成功数",0) WHEN 0 THEN 0 ELSE round(NVl(t2."邮件2",0)/s."成功数",4)*100 END) 邮件2转化率,
(CASE NVl(s."成功数",0) WHEN 0 THEN 0 ELSE round(NVl(t3."邮件3",0)/s."成功数",4)*100 END) 邮件3转化率,
(CASE NVl(s."成功数",0) WHEN 0 THEN 0 ELSE round(NVl(t4."邮件4",0)/s."成功数",4)*100 END) 邮件4转化率,
(CASE NVl(s."成功数",0) WHEN 0 THEN 0 ELSE round(NVl(t5."邮件5",0)/s."成功数",4)*100 END) 邮件5转化率,
(CASE NVl(s."成功数",0) WHEN 0 THEN 0 ELSE round(NVl(t6."邮件6",0)/s."成功数",4)*100 END) 邮件6转化率,
(CASE NVl(s."成功数",0) WHEN 0 THEN 0 ELSE round(NVl(t7."邮件7",0)/s."成功数",4)*100 END) 邮件7转化率,
(CASE NVl(s."成功数",0) WHEN 0 THEN 0 ELSE round(NVl(t8."邮件8",0)/s."成功数",4)*100 END) 邮件8转化率,
(CASE NVl(s."成功数",0) WHEN 0 THEN 0 ELSE round(NVl(t9."邮件9",0)/s."成功数",4)*100 END) 邮件9转化率,
(CASE NVl(s."成功数",0) WHEN 0 THEN 0 ELSE round(NVl(t10."邮件10",0)/s."成功数",4)*100 END) 邮件10转化率,
(CASE NVl(s."成功数",0) WHEN 0 THEN 0 ELSE round(NVl(t20."邮件20",0)/s."成功数",4)*100 END) 邮件20转化率

from (select DISTINCT SALESMANNO,SALESMANNAME 姓名 FROM CALLOUTDATA WHERE SALESMANNO IS NOT NULL AND SALESMANNAME IS NOT NULL) t
LEFT JOIN (select SALESMANNO,count(SALESMANNO) 下发名单量 FROM CALLOUTDATA GROUP BY SALESMANNO) f ON t.SALESMANNO = f.SALESMANNO
LEFT JOIN (select SALESMANNO,count(SALESMANNO) 成功数 FROM CALLOUTDATA WHERE LINKRESULT = '2' GROUP BY SALESMANNO) s ON t.SALESMANNO = s.SALESMANNO
LEFT JOIN (select SALESMANNO,count(SALESMANNO) 邮件1 FROM CALLOUTDATA WHERE EMAIL = '1' GROUP BY SALESMANNO) t1 ON t.SALESMANNO = t1.SALESMANNO
LEFT JOIN (select SALESMANNO,count(SALESMANNO) 邮件2 FROM CALLOUTDATA WHERE EMAIL = '2' GROUP BY SALESMANNO) t2 ON t.SALESMANNO = t2.SALESMANNO
LEFT JOIN (select SALESMANNO,count(SALESMANNO) 邮件3 FROM CALLOUTDATA WHERE EMAIL = '3' GROUP BY SALESMANNO) t3 ON t.SALESMANNO = t3.SALESMANNO
LEFT JOIN (select SALESMANNO,count(SALESMANNO) 邮件4 FROM CALLOUTDATA WHERE EMAIL = '4' GROUP BY SALESMANNO) t4 ON t.SALESMANNO = t4.SALESMANNO
LEFT JOIN (select SALESMANNO,count(SALESMANNO) 邮件5 FROM CALLOUTDATA WHERE EMAIL = '5' GROUP BY SALESMANNO) t5 ON t.SALESMANNO = t5.SALESMANNO
LEFT JOIN (select SALESMANNO,count(SALESMANNO) 邮件6 FROM CALLOUTDATA WHERE EMAIL = '6' GROUP BY SALESMANNO) t6 ON t.SALESMANNO = t6.SALESMANNO
LEFT JOIN (select SALESMANNO,count(SALESMANNO) 邮件7 FROM CALLOUTDATA WHERE EMAIL = '7' GROUP BY SALESMANNO) t7 ON t.SALESMANNO = t7.SALESMANNO
LEFT JOIN (select SALESMANNO,count(SALESMANNO) 邮件8 FROM CALLOUTDATA WHERE EMAIL = '8' GROUP BY SALESMANNO) t8 ON t.SALESMANNO = t8.SALESMANNO
LEFT JOIN (select SALESMANNO,count(SALESMANNO) 邮件9 FROM CALLOUTDATA WHERE EMAIL = '9' GROUP BY SALESMANNO) t9 ON t.SALESMANNO = t9.SALESMANNO
LEFT JOIN (select SALESMANNO,count(SALESMANNO) 邮件10 FROM CALLOUTDATA WHERE EMAIL = '10' GROUP BY SALESMANNO) t10 ON t.SALESMANNO = t10.SALESMANNO
LEFT JOIN (select SALESMANNO,count(SALESMANNO) 邮件20 FROM CALLOUTDATA WHERE EMAIL = '20' GROUP BY SALESMANNO) t20 ON t.SALESMANNO = t20.SALESMANNO
)


